build: 
	@echo "Building Windows Target"
	@GOOS=windows go build -ldflags="-s -w" -o ./out/win/ -buildvcs=false ./cmd/...
	@echo "Building Linux Target"
	@GOOS=linux go build -ldflags="-s -w" -o ./out/linux/ -buildvcs=false ./cmd/... 
	@echo "Building Macos Target"
	@GOOS=darwin go build -ldflags="-s -w" -o ./out/macos/ -buildvcs=false ./cmd/...

